// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNRzjpuv_BUB40rMZPnNjEgHfse9ipGvc',
    appId: '1:179755954984:web:281168c0f69bc73735d61d',
    messagingSenderId: '179755954984',
    projectId: 'wallet-divisas',
    authDomain: 'wallet-divisas.firebaseapp.com',
    storageBucket: 'wallet-divisas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZPiFUkqXvBpvSd2XElMpoL4NSqy08xyk',
    appId: '1:179755954984:android:954f8a44842a73ae35d61d',
    messagingSenderId: '179755954984',
    projectId: 'wallet-divisas',
    storageBucket: 'wallet-divisas.firebasestorage.app',
  );



}
